// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"LuminaCode/agent"
	"LuminaCode/config"
	"context"
)

// Injectors from wire.go:

func initializeMemoryPreflight(ctx context.Context, cfg config.Config) (memoryPreflight, error) {
	configuredMemoryFabricFactory := agent.NewConfiguredMemoryFabricFactory()
	mainMemoryPreflight, err := provideMemoryPreflight(ctx, cfg, configuredMemoryFabricFactory)
	if err != nil {
		return memoryPreflight{}, err
	}
	return mainMemoryPreflight, nil
}

func initializePromptRuntime(cfg config.Config) (*PromptRuntime, func(), error) {
	configuredMemoryFabricFactory := agent.NewConfiguredMemoryFabricFactory()
	queryEngine, cleanup := providePromptEngine(cfg, configuredMemoryFabricFactory)
	store := provideSessionStore(cfg)
	promptRuntime := newPromptRuntime(queryEngine, store)
	return promptRuntime, func() {
		cleanup()
	}, nil
}

func initializeMemoryCommandRuntime(ctx context.Context, cfg config.Config) (*MemoryCommandRuntime, func(), error) {
	configuredMemoryFabricFactory := agent.NewConfiguredMemoryFabricFactory()
	fabricEngine, cleanup, err := provideMemoryCommandFabric(ctx, cfg, configuredMemoryFabricFactory)
	if err != nil {
		return nil, nil, err
	}
	memoryCommandRuntime := newMemoryCommandRuntime(fabricEngine)
	return memoryCommandRuntime, func() {
		cleanup()
	}, nil
}

func initializeRuntimeInspectionRuntime(ctx context.Context, opts RuntimeInspectionOptions) (*RuntimeInspectionRuntime, func(), error) {
	configConfig := provideRuntimeInspectionConfig(opts)
	mainRuntimeSessionID := provideRuntimeSessionID(opts)
	runtimeStore, cleanup, err := provideRuntimeJournal(ctx, configConfig, mainRuntimeSessionID)
	if err != nil {
		return nil, nil, err
	}
	configuredMemoryFabricFactory := agent.NewConfiguredMemoryFabricFactory()
	queryEngine, cleanup2 := providePromptEngine(configConfig, configuredMemoryFabricFactory)
	runtimeAssembly, err := provideRuntimeAssembly(mainRuntimeSessionID, runtimeStore, queryEngine)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtimeInspectionRuntime := newRuntimeInspectionRuntime(runtimeStore, queryEngine, runtimeAssembly)
	return runtimeInspectionRuntime, func() {
		cleanup2()
		cleanup()
	}, nil
}

func initializeSessionStoreRuntime(opts SessionStoreOptions) *SessionStoreRuntime {
	store := provideConfiguredSessionStore(opts)
	sessionStoreRuntime := newSessionStoreRuntime(store)
	return sessionStoreRuntime
}
