// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package backend

import (
	"LuminaCode/agent"
	"LuminaCode/config"
	"context"
)

// Injectors from wire.go:

func initializeDaemonMemoryPreflight(ctx context.Context, cfg config.Config) (daemonMemoryPreflight, error) {
	configuredMemoryFabricFactory := agent.NewConfiguredMemoryFabricFactory()
	backendDaemonMemoryPreflight, err := ValidateDaemonMemory(ctx, cfg, configuredMemoryFabricFactory)
	if err != nil {
		return daemonMemoryPreflight{}, err
	}
	return backendDaemonMemoryPreflight, nil
}

func InitializeDaemonApp(ctx context.Context, opts DaemonOptions) (*DaemonApp, func(), error) {
	normalizedDaemonOptions := NormalizeDaemonOptions(opts)
	listener, cleanup, err := ProvideListener(normalizedDaemonOptions)
	if err != nil {
		return nil, nil, err
	}
	authToken, err := ProvideAuthToken()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	endpointInfo := ProvideEndpointInfo(normalizedDaemonOptions, listener, authToken)
	configConfig := ProvideDaemonConfig(normalizedDaemonOptions)
	store := ProvideSessionStore(configConfig)
	configuredMemoryFabricFactory := agent.NewConfiguredMemoryFabricFactory()
	defaultQueryEngineFactory := agent.NewQueryEngineFactory(configuredMemoryFabricFactory)
	eventHub, cleanup2 := ProvideEventHub()
	eventEmitter := ProvideEventEmitter(eventHub)
	sessionRuntimeFactory := NewSessionRuntimeFactory(configConfig, store, defaultQueryEngineFactory, eventEmitter)
	sessionManager, cleanup3 := ProvideSessionManager(configConfig, store, sessionRuntimeFactory)
	manager, cleanup4 := ProvideTeamManager(configConfig, defaultQueryEngineFactory, sessionManager, eventEmitter)
	shutdownSignal := NewShutdownSignal()
	upgrader := ProvideWebSocketUpgrader()
	daemonServer := NewDaemonServer(normalizedDaemonOptions, authToken, sessionManager, manager, eventHub, shutdownSignal, configuredMemoryFabricFactory, upgrader)
	handler := ProvideHTTPHandler(daemonServer)
	server := ProvideHTTPServer(handler)
	daemonApp := NewDaemonApp(normalizedDaemonOptions, endpointInfo, listener, server, daemonServer, shutdownSignal)
	return daemonApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
